name: publish

on:
  # Trigger this workflow when a release is created.
  release:
    types:
      - published

permissions:
  # Allow checkout of the project.
  contents: read

env:
  # Default Python version on which jobs are run.
  DEFAULT_PYTHON_VERSION: '3.9'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install build frontend
        run: python -m pip install build
      - name: Build distribution package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
